import "./globals.css";
import type { Metadata } from "next";
import { Lora, Nunito } from "next/font/google";

const lora = Lora({
  subsets: ["latin"],
  display: "swap",
  weight: ["600", "700"],
  variable: "--font-lora",
});
const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lora.variable}${nunito.variable}`}>{children}</body>
    </html>
  );
}
